const CREATE_CUSTOMER = "customer:CREATE_CUSTOMER";
const CREATE_ADDRESS = "customer:CREATE_ADDRESS";
const GET_CUSTOMER = "customer:GET_CUSTOMER";
const EDIT_CUSTOMER = "customer:EDIT_CUSTOMER";
const EDIT_CUSTOMER_ADDRESS = "customer:EDIT_CUSTOMER_ADDRESS";

module.exports = {
    CREATE_CUSTOMER,
    CREATE_ADDRESS,
    GET_CUSTOMER,
    EDIT_CUSTOMER,
    EDIT_CUSTOMER_ADDRESS,
}